package com.alticeusa.ds.svodusagedemographics.avro;
/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
@SuppressWarnings("all")
/**  */
@org.apache.avro.specific.AvroGenerated
public class KomCustomerAccount extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"incoming.kom_customer_account\",\"doc\":\"\",\"fields\":[{\"name\":\"encrypted_customer_account_id\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null,\"columnname\":\"encrypted_customer_account_id\",\"sqltype\":\"-5\"},{\"name\":\"encrypted_chc_id\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null,\"columnname\":\"encrypted_chc_id\",\"sqltype\":\"12\"},{\"name\":\"dtm_last_updated\",\"type\":[\"null\",\"long\"],\"default\":null,\"columnname\":\"dtm_last_updated\",\"sqltype\":\"93\"},{\"name\":\"dtm_created\",\"type\":[\"null\",\"long\"],\"default\":null,\"columnname\":\"dtm_created\",\"sqltype\":\"93\"}],\"tablename\":\"\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String encrypted_customer_account_id;
  @Deprecated public java.lang.String encrypted_chc_id;
  @Deprecated public java.lang.Long dtm_last_updated;
  @Deprecated public java.lang.Long dtm_created;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public KomCustomerAccount() {}

  /**
   * All-args constructor.
   */
  public KomCustomerAccount(java.lang.String encrypted_customer_account_id, java.lang.String encrypted_chc_id, java.lang.Long dtm_last_updated, java.lang.Long dtm_created) {
    this.encrypted_customer_account_id = encrypted_customer_account_id;
    this.encrypted_chc_id = encrypted_chc_id;
    this.dtm_last_updated = dtm_last_updated;
    this.dtm_created = dtm_created;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return encrypted_customer_account_id;
    case 1: return encrypted_chc_id;
    case 2: return dtm_last_updated;
    case 3: return dtm_created;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: encrypted_customer_account_id = (java.lang.String)value$; break;
    case 1: encrypted_chc_id = (java.lang.String)value$; break;
    case 2: dtm_last_updated = (java.lang.Long)value$; break;
    case 3: dtm_created = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'encrypted_customer_account_id' field.
   */
  public java.lang.String getEncryptedCustomerAccountId() {
    return encrypted_customer_account_id;
  }

  /**
   * Sets the value of the 'encrypted_customer_account_id' field.
   * @param value the value to set.
   */
  public void setEncryptedCustomerAccountId(java.lang.String value) {
    this.encrypted_customer_account_id = value;
  }

  /**
   * Gets the value of the 'encrypted_chc_id' field.
   */
  public java.lang.String getEncryptedChcId() {
    return encrypted_chc_id;
  }

  /**
   * Sets the value of the 'encrypted_chc_id' field.
   * @param value the value to set.
   */
  public void setEncryptedChcId(java.lang.String value) {
    this.encrypted_chc_id = value;
  }

  /**
   * Gets the value of the 'dtm_last_updated' field.
   */
  public java.lang.Long getDtmLastUpdated() {
    return dtm_last_updated;
  }

  /**
   * Sets the value of the 'dtm_last_updated' field.
   * @param value the value to set.
   */
  public void setDtmLastUpdated(java.lang.Long value) {
    this.dtm_last_updated = value;
  }

  /**
   * Gets the value of the 'dtm_created' field.
   */
  public java.lang.Long getDtmCreated() {
    return dtm_created;
  }

  /**
   * Sets the value of the 'dtm_created' field.
   * @param value the value to set.
   */
  public void setDtmCreated(java.lang.Long value) {
    this.dtm_created = value;
  }

  /** Creates a new KomCustomerAccount RecordBuilder */
  public static KomCustomerAccount.Builder newBuilder() {
    return new KomCustomerAccount.Builder();
  }
  
  /** Creates a new KomCustomerAccount RecordBuilder by copying an existing Builder */
  public static KomCustomerAccount.Builder newBuilder(KomCustomerAccount.Builder other) {
    return new KomCustomerAccount.Builder(other);
  }
  
  /** Creates a new KomCustomerAccount RecordBuilder by copying an existing KomCustomerAccount instance */
  public static KomCustomerAccount.Builder newBuilder(KomCustomerAccount other) {
    return new KomCustomerAccount.Builder(other);
  }
  
  /**
   * RecordBuilder for KomCustomerAccount instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<KomCustomerAccount>
    implements org.apache.avro.data.RecordBuilder<KomCustomerAccount> {

    private java.lang.String encrypted_customer_account_id;
    private java.lang.String encrypted_chc_id;
    private java.lang.Long dtm_last_updated;
    private java.lang.Long dtm_created;

    /** Creates a new Builder */
    private Builder() {
      super(KomCustomerAccount.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(KomCustomerAccount.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.encrypted_customer_account_id)) {
        this.encrypted_customer_account_id = data().deepCopy(fields()[0].schema(), other.encrypted_customer_account_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.encrypted_chc_id)) {
        this.encrypted_chc_id = data().deepCopy(fields()[1].schema(), other.encrypted_chc_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.dtm_last_updated)) {
        this.dtm_last_updated = data().deepCopy(fields()[2].schema(), other.dtm_last_updated);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.dtm_created)) {
        this.dtm_created = data().deepCopy(fields()[3].schema(), other.dtm_created);
        fieldSetFlags()[3] = true;
      }
    }
    
    /** Creates a Builder by copying an existing KomCustomerAccount instance */
    private Builder(KomCustomerAccount other) {
            super(KomCustomerAccount.SCHEMA$);
      if (isValidValue(fields()[0], other.encrypted_customer_account_id)) {
        this.encrypted_customer_account_id = data().deepCopy(fields()[0].schema(), other.encrypted_customer_account_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.encrypted_chc_id)) {
        this.encrypted_chc_id = data().deepCopy(fields()[1].schema(), other.encrypted_chc_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.dtm_last_updated)) {
        this.dtm_last_updated = data().deepCopy(fields()[2].schema(), other.dtm_last_updated);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.dtm_created)) {
        this.dtm_created = data().deepCopy(fields()[3].schema(), other.dtm_created);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'encrypted_customer_account_id' field */
    public java.lang.String getEncryptedCustomerAccountId() {
      return encrypted_customer_account_id;
    }
    
    /** Sets the value of the 'encrypted_customer_account_id' field */
    public KomCustomerAccount.Builder setEncryptedCustomerAccountId(java.lang.String value) {
      validate(fields()[0], value);
      this.encrypted_customer_account_id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'encrypted_customer_account_id' field has been set */
    public boolean hasEncryptedCustomerAccountId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'encrypted_customer_account_id' field */
    public KomCustomerAccount.Builder clearEncryptedCustomerAccountId() {
      encrypted_customer_account_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'encrypted_chc_id' field */
    public java.lang.String getEncryptedChcId() {
      return encrypted_chc_id;
    }
    
    /** Sets the value of the 'encrypted_chc_id' field */
    public KomCustomerAccount.Builder setEncryptedChcId(java.lang.String value) {
      validate(fields()[1], value);
      this.encrypted_chc_id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'encrypted_chc_id' field has been set */
    public boolean hasEncryptedChcId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'encrypted_chc_id' field */
    public KomCustomerAccount.Builder clearEncryptedChcId() {
      encrypted_chc_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'dtm_last_updated' field */
    public java.lang.Long getDtmLastUpdated() {
      return dtm_last_updated;
    }
    
    /** Sets the value of the 'dtm_last_updated' field */
    public KomCustomerAccount.Builder setDtmLastUpdated(java.lang.Long value) {
      validate(fields()[2], value);
      this.dtm_last_updated = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'dtm_last_updated' field has been set */
    public boolean hasDtmLastUpdated() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'dtm_last_updated' field */
    public KomCustomerAccount.Builder clearDtmLastUpdated() {
      dtm_last_updated = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'dtm_created' field */
    public java.lang.Long getDtmCreated() {
      return dtm_created;
    }
    
    /** Sets the value of the 'dtm_created' field */
    public KomCustomerAccount.Builder setDtmCreated(java.lang.Long value) {
      validate(fields()[3], value);
      this.dtm_created = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'dtm_created' field has been set */
    public boolean hasDtmCreated() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'dtm_created' field */
    public KomCustomerAccount.Builder clearDtmCreated() {
      dtm_created = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public KomCustomerAccount build() {
      try {
        KomCustomerAccount record = new KomCustomerAccount();
        record.encrypted_customer_account_id = fieldSetFlags()[0] ? this.encrypted_customer_account_id : (java.lang.String) defaultValue(fields()[0]);
        record.encrypted_chc_id = fieldSetFlags()[1] ? this.encrypted_chc_id : (java.lang.String) defaultValue(fields()[1]);
        record.dtm_last_updated = fieldSetFlags()[2] ? this.dtm_last_updated : (java.lang.Long) defaultValue(fields()[2]);
        record.dtm_created = fieldSetFlags()[3] ? this.dtm_created : (java.lang.Long) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
