package com.alticeusa.ds.svodusagedemographics.avro;
/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
@SuppressWarnings("all")
/**  */
@org.apache.avro.specific.AvroGenerated
public class KomVodOrder extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"incoming.kom_vod_order\",\"doc\":\"\",\"fields\":[{\"name\":\"encrypted_customer_account_id\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null,\"columnname\":\"encrypted_customer_account_id\",\"sqltype\":\"-5\"},{\"name\":\"vod_order_id\",\"type\":[\"null\",\"long\"],\"default\":null,\"columnname\":\"vod_order_id\",\"sqltype\":\"12\"},{\"name\":\"corp\",\"type\":[\"null\",\"long\"],\"default\":null,\"columnname\":\"corp\",\"sqltype\":\"12\"},{\"name\":\"preview_ind\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null,\"columnname\":\"preview_ind\",\"sqltype\":\"12\"},{\"name\":\"trailer_ind\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null,\"columnname\":\"trailer_ind\",\"sqltype\":\"93\"},{\"name\":\"dtm_created\",\"type\":[\"null\",\"long\"],\"default\":null,\"columnname\":\"dtm_created\",\"sqltype\":\"93\"}],\"tablename\":\"\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String encrypted_customer_account_id;
  @Deprecated public java.lang.Long vod_order_id;
  @Deprecated public java.lang.Long corp;
  @Deprecated public java.lang.String preview_ind;
  @Deprecated public java.lang.String trailer_ind;
  @Deprecated public java.lang.Long dtm_created;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public KomVodOrder() {}

  /**
   * All-args constructor.
   */
  public KomVodOrder(java.lang.String encrypted_customer_account_id, java.lang.Long vod_order_id, java.lang.Long corp, java.lang.String preview_ind, java.lang.String trailer_ind, java.lang.Long dtm_created) {
    this.encrypted_customer_account_id = encrypted_customer_account_id;
    this.vod_order_id = vod_order_id;
    this.corp = corp;
    this.preview_ind = preview_ind;
    this.trailer_ind = trailer_ind;
    this.dtm_created = dtm_created;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return encrypted_customer_account_id;
    case 1: return vod_order_id;
    case 2: return corp;
    case 3: return preview_ind;
    case 4: return trailer_ind;
    case 5: return dtm_created;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: encrypted_customer_account_id = (java.lang.String)value$; break;
    case 1: vod_order_id = (java.lang.Long)value$; break;
    case 2: corp = (java.lang.Long)value$; break;
    case 3: preview_ind = (java.lang.String)value$; break;
    case 4: trailer_ind = (java.lang.String)value$; break;
    case 5: dtm_created = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'encrypted_customer_account_id' field.
   */
  public java.lang.String getEncryptedCustomerAccountId() {
    return encrypted_customer_account_id;
  }

  /**
   * Sets the value of the 'encrypted_customer_account_id' field.
   * @param value the value to set.
   */
  public void setEncryptedCustomerAccountId(java.lang.String value) {
    this.encrypted_customer_account_id = value;
  }

  /**
   * Gets the value of the 'vod_order_id' field.
   */
  public java.lang.Long getVodOrderId() {
    return vod_order_id;
  }

  /**
   * Sets the value of the 'vod_order_id' field.
   * @param value the value to set.
   */
  public void setVodOrderId(java.lang.Long value) {
    this.vod_order_id = value;
  }

  /**
   * Gets the value of the 'corp' field.
   */
  public java.lang.Long getCorp() {
    return corp;
  }

  /**
   * Sets the value of the 'corp' field.
   * @param value the value to set.
   */
  public void setCorp(java.lang.Long value) {
    this.corp = value;
  }

  /**
   * Gets the value of the 'preview_ind' field.
   */
  public java.lang.String getPreviewInd() {
    return preview_ind;
  }

  /**
   * Sets the value of the 'preview_ind' field.
   * @param value the value to set.
   */
  public void setPreviewInd(java.lang.String value) {
    this.preview_ind = value;
  }

  /**
   * Gets the value of the 'trailer_ind' field.
   */
  public java.lang.String getTrailerInd() {
    return trailer_ind;
  }

  /**
   * Sets the value of the 'trailer_ind' field.
   * @param value the value to set.
   */
  public void setTrailerInd(java.lang.String value) {
    this.trailer_ind = value;
  }

  /**
   * Gets the value of the 'dtm_created' field.
   */
  public java.lang.Long getDtmCreated() {
    return dtm_created;
  }

  /**
   * Sets the value of the 'dtm_created' field.
   * @param value the value to set.
   */
  public void setDtmCreated(java.lang.Long value) {
    this.dtm_created = value;
  }

  /** Creates a new KomVodOrder RecordBuilder */
  public static KomVodOrder.Builder newBuilder() {
    return new KomVodOrder.Builder();
  }
  
  /** Creates a new KomVodOrder RecordBuilder by copying an existing Builder */
  public static KomVodOrder.Builder newBuilder(KomVodOrder.Builder other) {
    return new KomVodOrder.Builder(other);
  }
  
  /** Creates a new KomVodOrder RecordBuilder by copying an existing KomVodOrder instance */
  public static KomVodOrder.Builder newBuilder(KomVodOrder other) {
    return new KomVodOrder.Builder(other);
  }
  
  /**
   * RecordBuilder for KomVodOrder instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<KomVodOrder>
    implements org.apache.avro.data.RecordBuilder<KomVodOrder> {

    private java.lang.String encrypted_customer_account_id;
    private java.lang.Long vod_order_id;
    private java.lang.Long corp;
    private java.lang.String preview_ind;
    private java.lang.String trailer_ind;
    private java.lang.Long dtm_created;

    /** Creates a new Builder */
    private Builder() {
      super(KomVodOrder.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(KomVodOrder.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.encrypted_customer_account_id)) {
        this.encrypted_customer_account_id = data().deepCopy(fields()[0].schema(), other.encrypted_customer_account_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.vod_order_id)) {
        this.vod_order_id = data().deepCopy(fields()[1].schema(), other.vod_order_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.corp)) {
        this.corp = data().deepCopy(fields()[2].schema(), other.corp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.preview_ind)) {
        this.preview_ind = data().deepCopy(fields()[3].schema(), other.preview_ind);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.trailer_ind)) {
        this.trailer_ind = data().deepCopy(fields()[4].schema(), other.trailer_ind);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.dtm_created)) {
        this.dtm_created = data().deepCopy(fields()[5].schema(), other.dtm_created);
        fieldSetFlags()[5] = true;
      }
    }
    
    /** Creates a Builder by copying an existing KomVodOrder instance */
    private Builder(KomVodOrder other) {
            super(KomVodOrder.SCHEMA$);
      if (isValidValue(fields()[0], other.encrypted_customer_account_id)) {
        this.encrypted_customer_account_id = data().deepCopy(fields()[0].schema(), other.encrypted_customer_account_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.vod_order_id)) {
        this.vod_order_id = data().deepCopy(fields()[1].schema(), other.vod_order_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.corp)) {
        this.corp = data().deepCopy(fields()[2].schema(), other.corp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.preview_ind)) {
        this.preview_ind = data().deepCopy(fields()[3].schema(), other.preview_ind);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.trailer_ind)) {
        this.trailer_ind = data().deepCopy(fields()[4].schema(), other.trailer_ind);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.dtm_created)) {
        this.dtm_created = data().deepCopy(fields()[5].schema(), other.dtm_created);
        fieldSetFlags()[5] = true;
      }
    }

    /** Gets the value of the 'encrypted_customer_account_id' field */
    public java.lang.String getEncryptedCustomerAccountId() {
      return encrypted_customer_account_id;
    }
    
    /** Sets the value of the 'encrypted_customer_account_id' field */
    public KomVodOrder.Builder setEncryptedCustomerAccountId(java.lang.String value) {
      validate(fields()[0], value);
      this.encrypted_customer_account_id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'encrypted_customer_account_id' field has been set */
    public boolean hasEncryptedCustomerAccountId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'encrypted_customer_account_id' field */
    public KomVodOrder.Builder clearEncryptedCustomerAccountId() {
      encrypted_customer_account_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'vod_order_id' field */
    public java.lang.Long getVodOrderId() {
      return vod_order_id;
    }
    
    /** Sets the value of the 'vod_order_id' field */
    public KomVodOrder.Builder setVodOrderId(java.lang.Long value) {
      validate(fields()[1], value);
      this.vod_order_id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'vod_order_id' field has been set */
    public boolean hasVodOrderId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'vod_order_id' field */
    public KomVodOrder.Builder clearVodOrderId() {
      vod_order_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'corp' field */
    public java.lang.Long getCorp() {
      return corp;
    }
    
    /** Sets the value of the 'corp' field */
    public KomVodOrder.Builder setCorp(java.lang.Long value) {
      validate(fields()[2], value);
      this.corp = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'corp' field has been set */
    public boolean hasCorp() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'corp' field */
    public KomVodOrder.Builder clearCorp() {
      corp = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'preview_ind' field */
    public java.lang.String getPreviewInd() {
      return preview_ind;
    }
    
    /** Sets the value of the 'preview_ind' field */
    public KomVodOrder.Builder setPreviewInd(java.lang.String value) {
      validate(fields()[3], value);
      this.preview_ind = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'preview_ind' field has been set */
    public boolean hasPreviewInd() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'preview_ind' field */
    public KomVodOrder.Builder clearPreviewInd() {
      preview_ind = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'trailer_ind' field */
    public java.lang.String getTrailerInd() {
      return trailer_ind;
    }
    
    /** Sets the value of the 'trailer_ind' field */
    public KomVodOrder.Builder setTrailerInd(java.lang.String value) {
      validate(fields()[4], value);
      this.trailer_ind = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'trailer_ind' field has been set */
    public boolean hasTrailerInd() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'trailer_ind' field */
    public KomVodOrder.Builder clearTrailerInd() {
      trailer_ind = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'dtm_created' field */
    public java.lang.Long getDtmCreated() {
      return dtm_created;
    }
    
    /** Sets the value of the 'dtm_created' field */
    public KomVodOrder.Builder setDtmCreated(java.lang.Long value) {
      validate(fields()[5], value);
      this.dtm_created = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'dtm_created' field has been set */
    public boolean hasDtmCreated() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'dtm_created' field */
    public KomVodOrder.Builder clearDtmCreated() {
      dtm_created = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    public KomVodOrder build() {
      try {
        KomVodOrder record = new KomVodOrder();
        record.encrypted_customer_account_id = fieldSetFlags()[0] ? this.encrypted_customer_account_id : (java.lang.String) defaultValue(fields()[0]);
        record.vod_order_id = fieldSetFlags()[1] ? this.vod_order_id : (java.lang.Long) defaultValue(fields()[1]);
        record.corp = fieldSetFlags()[2] ? this.corp : (java.lang.Long) defaultValue(fields()[2]);
        record.preview_ind = fieldSetFlags()[3] ? this.preview_ind : (java.lang.String) defaultValue(fields()[3]);
        record.trailer_ind = fieldSetFlags()[4] ? this.trailer_ind : (java.lang.String) defaultValue(fields()[4]);
        record.dtm_created = fieldSetFlags()[5] ? this.dtm_created : (java.lang.Long) defaultValue(fields()[5]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
