--######################################################################################################################
--#   This source code is the property of:
--#   Cablevision Systems Corporation, Inc. (c) 2015
--#   1111 Stewart Avenue, Bethpage, NY 11714
--#   www.cablevision.com
--#   Department: AM
--#
--#   Program name: module.hql
--#   Program type: Hive Query Language script
--#   Purpose:    : Create incoming_hit_data table at Incoming layer
--#   Author(s)   : DataMetica Team
--#   Usage       : beeline -u  <url> -n <username> -p <password> -hivevar var1=var1 -f module.hql
--#   Date        : 09/12/2016
--#   Log File    : .../log/${job_name}.log
--#   SQL File    : 
--#   Error File  : .../log/${job_name}.log
--#   Dependency  : 
--#   Disclaimer  : 
--#
--#   Modification History :
--#   =======================
--#
--#    ver     who                      date             comments
--#   ------   --------------------     ----------       -------------------------------------
--#    1.0     DataMetica Team          09/12/2016       Initial version
--#
--#
--#####################################################################################################################

DROP TABLE IF EXISTS ${hivevar:database}.${hivevar:table_prefix}${hivevar:table_name};

CREATE EXTERNAL TABLE ${hivevar:database}.${hivevar:table_prefix}${hivevar:table_name}
(
hit_time_gmt                    decimal(38,0) COMMENT '' ,
service                         VARCHAR(255)  COMMENT '' ,
accept_language                 VARCHAR(255)  COMMENT '' ,
date_time                       TIMESTAMP    COMMENT ''  ,
visid_high                      VARCHAR(255)  COMMENT ''  ,
visid_low                       VARCHAR(255)  COMMENT ''  ,
event_list                      VARCHAR(255)  COMMENT ''  ,
homepage                        char(1)       COMMENT '' ,
ip                              VARCHAR(255)  COMMENT ''  ,
page_event                       decimal(38,0) COMMENT '' ,
page_event_var1                 VARCHAR(500)  COMMENT ''  ,
page_event_var2                 VARCHAR(255)  COMMENT ''  ,
page_type                       VARCHAR(255)  COMMENT ''  ,
page_url                        VARCHAR(255)  COMMENT ''  ,
pagename                        VARCHAR(255)  COMMENT '' ,
product_list                    VARCHAR(255)  COMMENT ''  ,
user_server                     VARCHAR(255)  COMMENT ''  ,
channel                         VARCHAR(255)  COMMENT ''  ,
prop1                           VARCHAR(255)  COMMENT ''  ,
prop2                           VARCHAR(255)  COMMENT ''  ,
prop3                           VARCHAR(255)  COMMENT ''  ,
prop4                           VARCHAR(255)  COMMENT ''  ,
prop5                           VARCHAR(255)  COMMENT ''  ,
prop6                           VARCHAR(255)  COMMENT ''  ,
prop7                           VARCHAR(255)  COMMENT ''  ,
prop8                           VARCHAR(255)  COMMENT ''  ,
prop9                           VARCHAR(255)  COMMENT ''  ,
prop10                          VARCHAR(255)  COMMENT ''  ,
prop11                          VARCHAR(255)  COMMENT ''  ,
prop12                          VARCHAR(255)  COMMENT ''  ,
prop13                          VARCHAR(255)  COMMENT ''  ,
prop14                          VARCHAR(255)  COMMENT ''  ,
prop15                          VARCHAR(255)  COMMENT ''  ,
prop16                          VARCHAR(255)  COMMENT ''  ,
prop17                          VARCHAR(255)  COMMENT ''  ,
prop18                          VARCHAR(255)  COMMENT ''  ,
prop19                          VARCHAR(255)  COMMENT ''  ,
prop20                          VARCHAR(255)  COMMENT ''  ,
prop21                          VARCHAR(255)  COMMENT ''  ,
prop22                          VARCHAR(255)  COMMENT ''  ,
prop23                          VARCHAR(255)  COMMENT ''  ,
prop24                          VARCHAR(255)  COMMENT ''  ,
prop25                          VARCHAR(255)  COMMENT ''  ,
prop26                          VARCHAR(255)  COMMENT ''  ,
prop27                          VARCHAR(255)  COMMENT ''  ,
prop28                          VARCHAR(255)  COMMENT ''  ,
prop29                          VARCHAR(255)  COMMENT ''  ,
prop30                          VARCHAR(255)  COMMENT ''  ,
prop31                          VARCHAR(255)  COMMENT ''  ,
prop32                          VARCHAR(255)  COMMENT ''  ,
prop33                          VARCHAR(255)  COMMENT ''  ,
prop34                          VARCHAR(255)  COMMENT ''  ,
prop35                          VARCHAR(255)  COMMENT ''  ,
prop36                          VARCHAR(255)  COMMENT ''  ,
prop37                          VARCHAR(255)  COMMENT ''  ,
prop38                          VARCHAR(255)  COMMENT ''  ,
prop39                          VARCHAR(255)  COMMENT ''  ,
prop40                          VARCHAR(255)  COMMENT ''  ,
prop41                          VARCHAR(255)  COMMENT ''  ,
prop42                          VARCHAR(255)  COMMENT ''  ,
prop43                          VARCHAR(255)  COMMENT ''  ,
prop44                          VARCHAR(255)  COMMENT ''  ,
prop45                          VARCHAR(255)  COMMENT ''  ,
prop46                          VARCHAR(255)  COMMENT ''  ,
prop47                          VARCHAR(255)  COMMENT ''  ,
prop48                          VARCHAR(255)  COMMENT ''  ,
prop49                          VARCHAR(255)  COMMENT '' ,
prop50                          VARCHAR(255)  COMMENT '' ,
purchaseid                      VARCHAR(255)  COMMENT '' ,  
referrer                        VARCHAR(255)  COMMENT '' ,
state                           VARCHAR(255)  COMMENT '' ,
user_agent                      VARCHAR(255)  COMMENT '' ,
zip                             VARCHAR(255)  COMMENT '' ,
search_engine                    decimal(38,0) COMMENT '' ,
exclude_hit                     decimal(38,0) COMMENT '' ,
hier1                           VARCHAR(255)  COMMENT '' ,
hier2                           VARCHAR(255)  COMMENT '' ,
hier3                           VARCHAR(255)  COMMENT '' ,
hier4                           VARCHAR(255)  COMMENT '' ,
hier5                           VARCHAR(255)  COMMENT '' ,
browser                          decimal(38,0) COMMENT '' ,
post_browser_height              DECIMAL(38,0) COMMENT '' ,
post_browser_width               DECIMAL(38,0) COMMENT '' ,
post_cookies                    VARCHAR(255)  COMMENT '' ,
post_java_enabled               VARCHAR(255)  COMMENT '' ,
post_persistent_cookie          VARCHAR(255)  COMMENT '' ,
color                           VARCHAR(255)  COMMENT '' ,
connection_type                 DECIMAL(38,0) COMMENT '' ,
country                         decimal(38,0) COMMENT '' ,
domain                          VARCHAR(255)  COMMENT '' ,
post_t_time_info                VARCHAR(255)  COMMENT '' ,
javascript                      DECIMAL(38,0) COMMENT '' ,
language                        decimal(38,0) COMMENT '' ,
os                              DECIMAL(38,0) COMMENT '' ,
plugins                         VARCHAR(255)  COMMENT '' ,
resolution                      DECIMAL(38,0) COMMENT '' ,
last_hit_time_gmt                decimal(38,0) COMMENT '' ,
first_hit_time_gmt               decimal(38,0) COMMENT '' ,
visit_start_time_gmt            decimal(38,0) COMMENT '' ,
last_purchase_time_gmt          DECIMAL(38,0) COMMENT '' ,
last_purchase_num               DECIMAL(38,0) COMMENT '' ,
first_hit_page_url              VARCHAR(255)  COMMENT '' ,
first_hit_pagename              VARCHAR(255)  COMMENT '' ,
visit_start_page_url            VARCHAR(255)  COMMENT ''  ,
visit_start_pagename            VARCHAR(255)  COMMENT ''  ,
first_hit_referrer              VARCHAR(255)  COMMENT ''  ,
visit_referrer                  VARCHAR(255)  COMMENT ''  ,
visit_search_engine              DECIMAL(38,0) COMMENT '' ,
visit_num                       decimal(38,0) COMMENT '' ,
visit_page_num                  decimal(38,0) COMMENT '' ,
prev_page                       decimal(38,0) COMMENT '' ,
geo_city                        VARCHAR(255)  COMMENT ''  ,
geo_country                     VARCHAR(255)  COMMENT ''  ,
geo_region                      VARCHAR(255)  COMMENT ''  ,
duplicate_purchase              decimal(38,0)  COMMENT '' ,
new_visit                       decimal(38,0)  COMMENT '' ,
daily_visitor                   decimal(38,0)  COMMENT '' ,
hourly_visitor                  decimal(38,0)  COMMENT '' ,
monthly_visitor                 decimal(38,0)  COMMENT '' ,
yearly_visitor                  decimal(38,0)  COMMENT '' ,
post_campaign                   VARCHAR(255)  COMMENT ''  ,
evar1                           VARCHAR(255)  COMMENT ''  ,
evar2                           VARCHAR(255)  COMMENT ''  ,
evar3                           VARCHAR(255)  COMMENT ''  ,
evar4                           VARCHAR(255)  COMMENT ''  ,
evar5                           VARCHAR(255)  COMMENT ''  ,
evar6                           VARCHAR(255)  COMMENT ''  ,
evar7                           VARCHAR(255)  COMMENT ''  ,
evar8                           VARCHAR(255)  COMMENT ''  ,
evar9                           VARCHAR(255)  COMMENT ''  ,
evar10                          VARCHAR(255)  COMMENT ''  ,
evar11                          VARCHAR(255)  COMMENT ''  ,
evar12                          VARCHAR(255)  COMMENT ''  ,
evar13                          VARCHAR(255)  COMMENT ''  ,
evar14                          VARCHAR(255)  COMMENT ''  ,
evar15                          VARCHAR(255)  COMMENT ''  ,
evar16                          VARCHAR(255)  COMMENT ''  ,
evar17                          VARCHAR(255)  COMMENT ''  ,
evar18                          VARCHAR(255)  COMMENT ''  ,
evar19                          VARCHAR(255)  COMMENT ''  ,
evar20                          VARCHAR(255)  COMMENT ''  ,
evar21                          VARCHAR(255)  COMMENT ''  ,
evar22                          VARCHAR(255)  COMMENT ''  ,
evar23                          VARCHAR(255)  COMMENT ''  ,
evar24                          VARCHAR(255)  COMMENT ''  ,
evar25                          VARCHAR(255)  COMMENT ''  ,
evar26                          VARCHAR(255)  COMMENT ''  ,
evar27                          VARCHAR(255)  COMMENT ''  ,
evar28                          VARCHAR(255)  COMMENT ''  ,
evar29                          VARCHAR(255)  COMMENT ''  ,
evar30                          VARCHAR(255)  COMMENT ''  ,
evar31                          VARCHAR(255)  COMMENT ''  ,
evar32                          VARCHAR(255)  COMMENT ''  ,
evar33                          VARCHAR(255)  COMMENT '' ,
evar34                          VARCHAR(255)  COMMENT '' ,
evar35                          VARCHAR(255)  COMMENT '' ,
evar36                          VARCHAR(255)  COMMENT ''  ,
evar37                          VARCHAR(255)  COMMENT '' ,
evar38                          VARCHAR(255)  COMMENT '' ,
evar39                          VARCHAR(255)  COMMENT '' ,
evar40                          VARCHAR(255)  COMMENT '' ,
evar41                          VARCHAR(255)  COMMENT '' ,
evar42                          VARCHAR(255)  COMMENT '' ,
evar43                          VARCHAR(255)  COMMENT '' ,
evar44                          VARCHAR(255)  COMMENT '' ,
evar45                          VARCHAR(255)  COMMENT '' ,
evar46                          VARCHAR(255)  COMMENT '' ,
evar47                          VARCHAR(255)  COMMENT '' ,
evar48                          VARCHAR(255)  COMMENT '' ,
evar49                          VARCHAR(255)  COMMENT '' ,
evar50                          VARCHAR(255)  COMMENT '' ,
post_evar1                      VARCHAR(255)  COMMENT '' ,
post_evar2                      VARCHAR(255)  COMMENT '' ,
post_evar3                      VARCHAR(255)  COMMENT '' ,
post_evar4                      VARCHAR(255)  COMMENT '' ,
post_evar5                      VARCHAR(255)  COMMENT '' ,
post_evar6                      VARCHAR(255)  COMMENT '' ,
post_evar7                      VARCHAR(255)  COMMENT '' ,
post_evar8                      VARCHAR(255)  COMMENT '' ,
post_evar9                      VARCHAR(255)  COMMENT '' ,
post_evar10                     VARCHAR(255)  COMMENT '' ,
post_evar11                     VARCHAR(255)  COMMENT '' ,
post_evar12                     VARCHAR(255)  COMMENT '' ,
post_evar13                     VARCHAR(255)  COMMENT '' ,
post_evar14                     VARCHAR(255)  COMMENT '' ,
post_evar15                     VARCHAR(255)  COMMENT '' ,
post_evar16                     VARCHAR(255)  COMMENT '' ,
post_evar17                     VARCHAR(255)  COMMENT '' ,
post_evar18                     VARCHAR(255)  COMMENT '' ,
post_evar19                     VARCHAR(255)  COMMENT '' ,
post_evar20                     VARCHAR(255)  COMMENT '' ,
post_evar21                     VARCHAR(255)  COMMENT '' ,
post_evar22                     VARCHAR(255)  COMMENT '' ,
post_evar23                     VARCHAR(255)  COMMENT '' ,
post_evar24                     VARCHAR(255)  COMMENT '' ,
post_evar25                     VARCHAR(255)  COMMENT '' ,
post_evar26                     VARCHAR(255)  COMMENT '' ,
post_evar27                     VARCHAR(255)  COMMENT '' ,
post_evar28                     VARCHAR(255)  COMMENT '' ,
post_evar29                     VARCHAR(255)  COMMENT '' ,
post_evar30                     VARCHAR(255)  COMMENT '' ,
post_evar31                     VARCHAR(255)  COMMENT '' ,
post_evar32                     VARCHAR(255)  COMMENT '' ,
post_evar33                     VARCHAR(255)  COMMENT '' ,
post_evar34                     VARCHAR(255)  COMMENT '' ,
post_evar35                     VARCHAR(255)  COMMENT '' ,
post_evar36                     VARCHAR(255)  COMMENT '' ,
post_evar37                     VARCHAR(255)  COMMENT '' ,
post_evar38                     VARCHAR(255)  COMMENT '' ,
post_evar39                     VARCHAR(255)  COMMENT '' ,
post_evar40                     VARCHAR(255)  COMMENT ''  ,
post_evar41                     VARCHAR(255)  COMMENT ''  ,
post_evar42                     VARCHAR(255)  COMMENT '' ,
post_evar43                     VARCHAR(255)  COMMENT '' ,
post_evar44                     VARCHAR(255)  COMMENT '' ,
post_evar45                     VARCHAR(255)  COMMENT '' ,
post_evar46                     VARCHAR(255)  COMMENT '' ,
post_evar47                     VARCHAR(255)  COMMENT '' ,
post_evar48                     VARCHAR(255)  COMMENT ''  ,
post_evar49                     VARCHAR(255)  COMMENT ''  ,
post_evar50                     VARCHAR(255)  COMMENT '' ,
click_action                    VARCHAR(255)  COMMENT ''  ,
click_action_type               VARCHAR(255)  COMMENT '' ,
click_context                   VARCHAR(255)  COMMENT '' ,
click_context_type              VARCHAR(255)  COMMENT ''  ,
click_sourceid                  VARCHAR(255)  COMMENT ''  ,
click_tag                       VARCHAR(255)  COMMENT '' 
)
PARTITIONED BY (SUITE_NAME STRING,
                SOURCE_DATE STRING)
ROW FORMAT DELIMITED 
   FIELDS TERMINATED BY '\t'
STORED AS TEXTFILE
LOCATION '${hivevar:location}'
TBLPROPERTIES ('serialization.null.format' = '');

--##############################################################################
--#                                    END                                     #
--##############################################################################