--######################################################################################################################
--#   This source code is the property of:
--#   Cablevision Systems Corporation, Inc. (c) 2015
--#   1111 Stewart Avenue, Bethpage, NY 11714
--#   www.cablevision.com
--#   Department: AM
--#
--#   Program name: module.hql
--#   Program type: Hive Query Language script
--#   Purpose:    : Create Work table(work_rsdvr_recordings_seq)
--#   Author(s)   : DataMetica Team
--#   Usage       : beeline -u  <url> -n <username> -p <password> -hivevar var1=var1 -f module.hql
--#   Date        : 05/05/2016
--#   Log File    : .../log/mrdvr/MRDVR_DEPLOYMENT.log
--#   SQL File    : 
--#   Error File  : .../log/mrdvr/MRDVR_DEPLOYMENT.log
--#   Dependency  : 
--#   Disclaimer  : 
--#
--#   Modification History :
--#   =======================
--#
--#    ver     who                      date             comments
--#   ------   --------------------     ----------       -------------------------------------
--#    1.0     DataMetica Team          05/05/2016       Initial version
--#
--#
--#####################################################################################################################

DROP TABLE IF EXISTS ${hivevar:database}.${hivevar:table_prefix}${hivevar:table_name}
;

CREATE TABLE ${hivevar:database}.${hivevar:table_prefix}${hivevar:table_name}
(  
   ASSET_ID_GOLD	                    BIGINT  COMMENT'Instance derived from gold table',
   ASSET_ID_INCOMING	                BIGINT  COMMENT'asset id as generated by the asset management system',
   CALL_SIGN_GOLD             	        VARCHAR(12) COMMENT'Instance derived from gold table',
   CALL_SIGN_INCOMING	                VARCHAR(12) COMMENT'callsign of the channel being recorded',
   CALL_SIGN_IND	                    VARCHAR(1) COMMENT'Column value modify indicator',
   CREATE_TIME_GOLD          	        TIMESTAMP COMMENT'Instance derived from gold table',
   CREATE_TIME_INCOMING	                TIMESTAMP COMMENT'date/time recording was created',
   CREATE_TIME_IND	                    VARCHAR(1) COMMENT'Column value modify indicator',
   DS_RECTIME_GOLD       	            TIMESTAMP COMMENT'Instance derived from gold table',
   DS_RECTIME_INCOMING	                TIMESTAMP COMMENT'rectime in Eastern Time',
   DS_RECTIME_IND	                    VARCHAR(1) COMMENT'Column value modify indicator',
   DS_STARTTIME_GOLD        	        TIMESTAMP COMMENT'Instance derived from gold table',
   DS_STARTTIME_INCOMING	            TIMESTAMP COMMENT'start_time in Eastern Time',
   DS_STARTTIME_IND	                    VARCHAR(1) COMMENT'Column value modify indicator',
   DTM_SYSDATE	                        TIMESTAMP COMMENT'',
   DURATION_GOLD      	                INT   COMMENT'',
   DURATION_INCOMING	                INT   COMMENT'duration of the recording in minutes',
   DURATION_IND	                        VARCHAR(1) COMMENT'Column value modify indicator',
   ENDTIME_ADJUSTMENT_PREV_GOLD	        BIGINT  COMMENT'Instance derived from gold table',
   ENDTIME_ADJUSTMENT_PREV_INCOMING	    BIGINT  COMMENT'',
   ENDTIME_ADJUSTMENT_PREV_IND	        VARCHAR(1) COMMENT'Column value modify indicator',
   ENDTIME_ADJUSTMENT_GOLD	            BIGINT  COMMENT'Instance derived from gold table',
   ENDTIME_ADJUSTMENT_INCOMING	        BIGINT  COMMENT'',
   ENDTIME_ADJUSTMENT_IND      	        VARCHAR(1) COMMENT'Column value modify indicator',
   HOME_ID_GOLD 	                    VARCHAR(255)  COMMENT'Instance derived from gold table',
   HOME_ID_INCOMING	                    VARCHAR(255)  COMMENT'',
   KEEP_TYPE_CODE_GOLD	                VARCHAR(4) COMMENT'Instance derived from gold table',
   KEEP_TYPE_CODE_INCOMING	            VARCHAR(4) COMMENT'',
   KEEP_TYPE_CODE_IND	                VARCHAR(1) COMMENT'Column value modify indicator',
   LAST_UPDATED_GOLD	                TIMESTAMP COMMENT'Instance derived from gold table',
   LAST_UPDATED_INCOMING	            TIMESTAMP COMMENT'',
   LAST_UPDATED_IND	                    VARCHAR(1) COMMENT'Column value modify indicator',
   LOAD_DATE                            TIMESTAMP COMMENT '',
   LOADTIME_GOLD	                    TIMESTAMP COMMENT'Instance derived from gold table',
   LOADTIME_INCOMING	                TIMESTAMP COMMENT'date and time data loaded into the DB',
   LOADTIME_IND	                        VARCHAR(1) COMMENT'Column value modify indicator',
   MODIFY_TIME_GOLD	                    TIMESTAMP COMMENT'Instance derived from gold table',
   MODIFY_TIME_INCOMING	                TIMESTAMP COMMENT'date/time the recording was modified',
   MODIFY_TIME_IND	                    VARCHAR(1) COMMENT'Column value modify indicator',
   OP_TYPE_GOLD                         VARCHAR(1) COMMENT'',
   OP_TYPE_I                  	        VARCHAR(1) COMMENT'',
   OP_TYPE_U                  	        VARCHAR(1) COMMENT'',
   PAUSE_TIME_GOLD	                    TIMESTAMP COMMENT'Instance derived from gold table',
   PAUSE_TIME_INCOMING	                TIMESTAMP COMMENT'the time of the pause that initiated this temporary recording. this will only be populated for recordings that were saved after a pause action',
   PAUSE_TIME_IND	                    VARCHAR(1) COMMENT'Column value modify indicator',
   RECORDING_DATE_GOLD	                TIMESTAMP COMMENT'Instance derived from gold table',
   RECORDING_DATE_INCOMING	            TIMESTAMP COMMENT'date of the recording',
   RECORDING_DATE_IND	                VARCHAR(1) COMMENT'Column value modify indicator',
   RECORDING_ID_GOLD	                BIGINT  COMMENT'Instance derived from gold table',
   RECORDING_ID_INCOMING	            BIGINT  COMMENT'unique id of the recording',
   RECORDING_LOCKED_GOLD	            BIGINT COMMENT'Instance derived from gold table',
   RECORDING_LOCKED_INCOMING	        BIGINT COMMENT'specified whether the recording is locked (parental controls)',
   RECORDING_LOCKED_IND	                VARCHAR(1) COMMENT'Column value modify indicator',
   RECORDING_STATUS_GOLD	            INT   COMMENT'Instance derived from gold table',
   RECORDING_STATUS_INCOMING	        INT   COMMENT'status of the recording - see lookup table for values',
   RECORDING_STATUS_IND	                VARCHAR(1) COMMENT'Column value modify indicator',
   RECORDING_TIME_GOLD	                VARCHAR(8)  COMMENT'Instance derived from gold table',
   RECORDING_TIME_INCOMING	            VARCHAR(8)  COMMENT'Start time of the recording',
   RECORDING_TIME_IND	                VARCHAR(1) COMMENT'Column value modify indicator',
   RSDVR_RECORDINGS_DELTA_SEQ           BIGINT COMMENT'',   
   SCHEDULE_ID_GOLD	                    BIGINT  COMMENT'Instance derived from gold table',
   SCHEDULE_ID_INCOMING	                BIGINT  COMMENT'links to the RSDVR_REQUESTS table',
   START_DATE_GOLD	                    TIMESTAMP COMMENT'Instance derived from gold table',
   START_DATE_INCOMING	                TIMESTAMP COMMENT'date recording is to start',
   START_DATE_IND	                    VARCHAR(1) COMMENT'Column value modify indicator',
   START_TIME_GOLD	                    VARCHAR(8) COMMENT'Instance derived from gold table',
   START_TIME_INCOMING	                VARCHAR(8) COMMENT'time recording is to start',
   START_TIME_IND	                    VARCHAR(1) COMMENT'Column value modify indicator',
   STARTDATE_STARTTIME_GOLD	            TIMESTAMP COMMENT'Instance derived from gold table',
   STARTDATE_STARTTIME_INCOMING	        TIMESTAMP COMMENT'start date time of the recording',
   STARTDATE_STARTTIME_IND	            VARCHAR(1) COMMENT'Column value modify indicator',
   TEMPORARY_ASSET_ID_GOLD	            BIGINT COMMENT'Instance derived from gold table',
   TEMPORARY_ASSET_ID_INCOMING	        BIGINT COMMENT'temporary asset id that will be used to turn this recording into a permanent one. this will only be populated for recordings that were saved after a pause action',
   TEMPORARY_ASSET_ID_IND	            VARCHAR(1) COMMENT'Column value modify indicator',
   Y_IND	                            VARCHAR(1) COMMENT'',
   CHANGEDFLAG                	        VARCHAR(10) COMMENT'',
   NEWFLAG                    	        VARCHAR(10) COMMENT''
)
STORED AS AVRO
LOCATION '${hivevar:location}'
;

--##############################################################################
--#                                    End                                     #
--##############################################################################