--######################################################################################################################
--#   This source code is the property of:
--#   Cablevision Systems Corporation, Inc. (c) 2015
--#   1111 Stewart Avenue, Bethpage, NY 11714
--#   www.cablevision.com
--#   Department: AM
--#
--#   Program name: module-transform.hql
--#   Program type: Hive Query Language script
--#   Purpose:    : Build GOLD_RSDVR_RECORDINGS_LAST_REC table 
--#   Author(s)   : DataMetica Team
--#   Usage       : beeline -u  <url> -n <username> -p <password> -hivevar var1=var1 -f module-transform.hql
--#   Date        : 12/28/2015
--#   Log File    : .../log/mrdvr/${job_name}.log
--#   SQL File    : 
--#   Error File  : .../log/mrdvr/${job_name}.log
--#   Dependency  : 
--#   Disclaimer  : 
--#
--#   Modification History :
--#   =======================
--#
--#    ver     who                      date             comments
--#   ------   --------------------     ----------       -------------------------------------
--#    1.0     DataMetica Team          12/28/2015       Initial version
--#
--#
--#####################################################################################################################

set hive.exec.dynamic.partition=true;
set hive.exec.dynamic.partition.mode=nonstrict;
set hive.cbo.enable=false;

INSERT OVERWRITE TABLE 
   ${hivevar:hive_database_name_gold}.${hivevar:gold_rsdvr_recordings_last_rec_tbl} 
SELECT 
   CASE 
      WHEN GOLD_RSDVR_RECORDINGS_LAST_REC.ASSET_ID IS NULL THEN WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.ASSET_ID 
   END AS ASSET_ID,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL 
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.CALL_SIGN 
               ELSE WORK_RSDVR_RECORDINGS_TMP.CALL_SIGN_INCOMING 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.CALL_SIGN 
   END AS CALL_SIGN,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL 
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.CALL_SIGN_IND 
               ELSE WORK_RSDVR_RECORDINGS_TMP.CALL_SIGN_IND 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.CALL_SIGN_IND 
   END AS CALL_SIGN_IND,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.CREATE_TIME 
               ELSE WORK_RSDVR_RECORDINGS_TMP.CREATE_TIME_INCOMING 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.CREATE_TIME 
   END AS CREATE_TIME,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.CREATE_TIME_IND 
               ELSE WORK_RSDVR_RECORDINGS_TMP.CREATE_TIME_IND 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.CREATE_TIME_IND 
   END AS CREATE_TIME_IND,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.DS_RECTIME 
               ELSE WORK_RSDVR_RECORDINGS_TMP.DS_RECTIME_INCOMING 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.DS_RECTIME 
   END AS DS_RECTIME,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.DS_RECTIME_IND 
               ELSE WORK_RSDVR_RECORDINGS_TMP.DS_RECTIME_IND 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.DS_RECTIME_IND 
   END AS DS_RECTIME_IND,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.DS_STARTTIME 
               ELSE WORK_RSDVR_RECORDINGS_TMP.DS_STARTTIME_INCOMING 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.DS_STARTTIME 
   END AS DS_STARTTIME,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.DS_STARTTIME_IND 
               ELSE WORK_RSDVR_RECORDINGS_TMP.DS_STARTTIME_IND 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.DS_STARTTIME_IND 
   END AS DS_STARTTIME_IND,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
            THEN ( 
               CASE 
                  WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL 
                     AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL  
                        THEN GOLD_RSDVR_RECORDINGS_LAST_REC.DTM_CREATED 
                  ELSE (
                      CASE 
                         WHEN WORK_RSDVR_RECORDINGS_TMP.NEWFLAG='TRUE' 
                            THEN  WORK_RSDVR_RECORDINGS_TMP.DTM_SYSDATE 
                         ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.DTM_CREATED 
                      END) 
               END )  
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.DTM_CREATED 
   END  AS DTM_CREATED,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
            THEN ( 
               CASE 
                  WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL 
                     AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL 
                        THEN GOLD_RSDVR_RECORDINGS_LAST_REC.DTM_LAST_MODIFIED 
                  ELSE WORK_RSDVR_RECORDINGS_TMP.DTM_SYSDATE 
               END ) 
   ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.DTM_LAST_MODIFIED 
   END  AS DTM_LAST_MODIFIED,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
      AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
      AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
      AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL 
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL  
                     THEN GOLD_RSDVR_RECORDINGS_LAST_REC.DTM_LAST_UPDATED 
               ELSE (
                  CASE 
                     WHEN WORK_RSDVR_RECORDINGS_TMP.NEWFLAG != 'TRUE' 
                        THEN WORK_RSDVR_RECORDINGS_TMP.DTM_SYSDATE 
                  END) 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.DTM_LAST_UPDATED 
   END  AS DTM_LAST_UPDATED,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.DURATION 
               ELSE WORK_RSDVR_RECORDINGS_TMP.DURATION_INCOMING 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.DURATION 
   END AS DURATION,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.DURATION_IND 
               ELSE WORK_RSDVR_RECORDINGS_TMP.DURATION_IND 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.DURATION_IND 
   END AS DURATION_IND,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.ENDTIME_ADJUSTMENT_PREV 
               ELSE WORK_RSDVR_RECORDINGS_TMP.ENDTIME_ADJUSTMENT_PREV_INCOMING 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.ENDTIME_ADJUSTMENT_PREV 
   END AS ENDTIME_ADJUSTMENT_PREV,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.ENDTIME_ADJUSTMENT_PREV_IND 
               ELSE WORK_RSDVR_RECORDINGS_TMP.ENDTIME_ADJUSTMENT_PREV_IND 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.ENDTIME_ADJUSTMENT_PREV_IND 
   END AS ENDTIME_ADJUSTMENT_PREV_IND,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.ENDTIME_ADJUSTMENT 
               ELSE WORK_RSDVR_RECORDINGS_TMP.ENDTIME_ADJUSTMENT_INCOMING 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.ENDTIME_ADJUSTMENT 
   END AS ENDTIME_ADJUSTMENT,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.ENDTIME_ADJUSTMENT_IND 
               ELSE WORK_RSDVR_RECORDINGS_TMP.ENDTIME_ADJUSTMENT_IND 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.ENDTIME_ADJUSTMENT_IND 
   END AS ENDTIME_ADJUSTMENT_IND,
   CASE 
      WHEN GOLD_RSDVR_RECORDINGS_LAST_REC.HOME_ID IS NULL THEN WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.HOME_ID 
   END AS HOME_ID,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.KEEP_TYPE_CODE 
               ELSE WORK_RSDVR_RECORDINGS_TMP.KEEP_TYPE_CODE_INCOMING 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.KEEP_TYPE_CODE 
   END AS KEEP_TYPE_CODE,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.KEEP_TYPE_CODE_IND 
               ELSE WORK_RSDVR_RECORDINGS_TMP.KEEP_TYPE_CODE_IND 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.KEEP_TYPE_CODE_IND 
   END AS KEEP_TYPE_CODE_IND,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.LAST_UPDATED 
               ELSE WORK_RSDVR_RECORDINGS_TMP.LAST_UPDATED_INCOMING 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.LAST_UPDATED 
   END AS LAST_UPDATED,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.LAST_UPDATED_IND 
               ELSE WORK_RSDVR_RECORDINGS_TMP.LAST_UPDATED_IND 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.LAST_UPDATED_IND 
   END AS LAST_UPDATED_IND,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.LOAD_DATE 
               ELSE WORK_RSDVR_RECORDINGS_TMP.LOAD_DATE 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.LOAD_DATE 
   END AS LOAD_DATE,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.LOADTIME 
               ELSE WORK_RSDVR_RECORDINGS_TMP.LOADTIME_INCOMING 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.LOADTIME 
   END AS LOADTIME,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.LOADTIME_IND 
               ELSE WORK_RSDVR_RECORDINGS_TMP.LOADTIME_IND 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.LOADTIME_IND 
   END AS LOADTIME_IND,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.MODIFY_TIME 
               ELSE WORK_RSDVR_RECORDINGS_TMP.MODIFY_TIME_INCOMING 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.MODIFY_TIME 
   END AS MODIFY_TIME,   
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.MODIFY_TIME_IND 
               ELSE WORK_RSDVR_RECORDINGS_TMP.MODIFY_TIME_IND 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.MODIFY_TIME_IND 
   END AS MODIFY_TIME_IND,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
               CASE 
                  WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG='TRUE' 
                  THEN WORK_RSDVR_RECORDINGS_TMP.OP_TYPE_U 
               ELSE WORK_RSDVR_RECORDINGS_TMP.OP_TYPE_I 
               END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.OP_TYPE 
   END AS OP_TYPE,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.PAUSE_TIME
               ELSE WORK_RSDVR_RECORDINGS_TMP.PAUSE_TIME_INCOMING 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.PAUSE_TIME 
   END AS PAUSE_TIME,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.PAUSE_TIME_IND
               ELSE WORK_RSDVR_RECORDINGS_TMP.PAUSE_TIME_IND 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.PAUSE_TIME_IND 
   END AS PAUSE_TIME_IND,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.RECORDING_DATE 
               ELSE WORK_RSDVR_RECORDINGS_TMP.RECORDING_DATE_INCOMING 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.RECORDING_DATE 
   END AS RECORDING_DATE,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.RECORDING_DATE_IND 
               ELSE WORK_RSDVR_RECORDINGS_TMP.RECORDING_DATE_IND 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.RECORDING_DATE_IND 
   END AS RECORDING_DATE_IND,
   CASE 
      WHEN GOLD_RSDVR_RECORDINGS_LAST_REC.RECORDING_ID IS NULL THEN WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.RECORDING_ID 
   END AS RECORDING_ID,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.RECORDING_LOCKED 
               ELSE WORK_RSDVR_RECORDINGS_TMP.RECORDING_LOCKED_INCOMING 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.RECORDING_LOCKED 
   END AS RECORDING_LOCKED,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.RECORDING_LOCKED_IND 
               ELSE WORK_RSDVR_RECORDINGS_TMP.RECORDING_LOCKED_IND 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.RECORDING_LOCKED_IND 
   END AS RECORDING_LOCKED_IND,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.RECORDING_STATUS 
               ELSE WORK_RSDVR_RECORDINGS_TMP.RECORDING_STATUS_INCOMING 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.RECORDING_STATUS 
   END AS RECORDING_STATUS,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.RECORDING_STATUS_IND 
               ELSE WORK_RSDVR_RECORDINGS_TMP.RECORDING_STATUS_IND 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.RECORDING_STATUS_IND 
   END AS RECORDING_STATUS_IND,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.RECORDING_TIME 
               ELSE WORK_RSDVR_RECORDINGS_TMP.RECORDING_TIME_INCOMING 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.RECORDING_TIME 
   END AS RECORDING_TIME,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.RECORDING_TIME_IND 
               ELSE WORK_RSDVR_RECORDINGS_TMP.RECORDING_TIME_IND 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.RECORDING_TIME_IND 
   END AS RECORDING_TIME_IND,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.RSDVR_RECORDINGS_DELTA_SEQ 
               ELSE WORK_RSDVR_RECORDINGS_TMP.RSDVR_RECORDINGS_DELTA_SEQ 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.RSDVR_RECORDINGS_DELTA_SEQ 
   END AS RSDVR_RECORDINGS_DELTA_SEQ,
   CASE 
      WHEN GOLD_RSDVR_RECORDINGS_LAST_REC.SCHEDULE_ID IS NULL THEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.SCHEDULE_ID 
   END AS SCHEDULE_ID,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.START_DATE 
               ELSE WORK_RSDVR_RECORDINGS_TMP.START_DATE_INCOMING 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.START_DATE 
   END AS START_DATE,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.START_DATE_IND 
               ELSE WORK_RSDVR_RECORDINGS_TMP.START_DATE_IND 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.START_DATE_IND 
   END AS START_DATE_IND,   
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.START_TIME 
               ELSE WORK_RSDVR_RECORDINGS_TMP.START_TIME_INCOMING 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.START_TIME 
   END AS START_TIME,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.START_TIME_IND 
               ELSE WORK_RSDVR_RECORDINGS_TMP.START_TIME_IND 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.START_TIME_IND 
   END AS START_TIME_IND,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.STARTDATE_STARTTIME 
               ELSE WORK_RSDVR_RECORDINGS_TMP.STARTDATE_STARTTIME_INCOMING 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.STARTDATE_STARTTIME 
   END AS STARTDATE_STARTTIME,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.STARTDATE_STARTTIME_IND 
               ELSE WORK_RSDVR_RECORDINGS_TMP.STARTDATE_STARTTIME_IND 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.STARTDATE_STARTTIME_IND 
   END AS STARTDATE_STARTTIME_IND,
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.TEMPORARY_ASSET_ID 
               ELSE WORK_RSDVR_RECORDINGS_TMP.TEMPORARY_ASSET_ID_INCOMING 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.TEMPORARY_ASSET_ID 
   END AS TEMPORARY_ASSET_ID,   
   CASE 
      WHEN WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING IS NOT NULL 
         AND WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING IS NOT NULL 
         THEN ( 
            CASE 
               WHEN WORK_RSDVR_RECORDINGS_TMP.CHANGEDFLAG IS NULL
                  AND WORK_RSDVR_RECORDINGS_TMP.NEWFLAG IS NULL THEN GOLD_RSDVR_RECORDINGS_LAST_REC.TEMPORARY_ASSET_ID_IND 
               ELSE WORK_RSDVR_RECORDINGS_TMP.TEMPORARY_ASSET_ID_IND 
            END ) 
      ELSE GOLD_RSDVR_RECORDINGS_LAST_REC.TEMPORARY_ASSET_ID_IND 
   END AS TEMPORARY_ASSET_ID_IND
FROM 
    ${hivevar:hive_database_name_gold}.${hivevar:gold_rsdvr_recordings_last_rec_tbl} GOLD_RSDVR_RECORDINGS_LAST_REC 
FULL OUTER JOIN ${hivevar:hive_database_name_work}.${hivevar:work_rsdvr_recordings_dedup_tbl} WORK_RSDVR_RECORDINGS_TMP 
ON
  ( GOLD_RSDVR_RECORDINGS_LAST_REC.SCHEDULE_ID = WORK_RSDVR_RECORDINGS_TMP.SCHEDULE_ID_INCOMING
 AND GOLD_RSDVR_RECORDINGS_LAST_REC.ASSET_ID = WORK_RSDVR_RECORDINGS_TMP.ASSET_ID_INCOMING 
 AND GOLD_RSDVR_RECORDINGS_LAST_REC.HOME_ID = WORK_RSDVR_RECORDINGS_TMP.HOME_ID_INCOMING
 AND GOLD_RSDVR_RECORDINGS_LAST_REC.RECORDING_ID = WORK_RSDVR_RECORDINGS_TMP.RECORDING_ID_INCOMING )
;

--##############################################################################
--#                                    End                                     #
--##############################################################################