--######################################################################################################################
--#   This source code is the property of:
--#   Cablevision Systems Corporation, Inc. (c) 2015
--#   1111 Stewart Avenue, Bethpage, NY 11714
--#   www.cablevision.com
--#   Department: AM
--#
--#   Program name: module.hql
--#   Program type: Hive Query Language script
--#   Purpose:    : Create Incoming table(incoming_ratecodes_tbl)
--#   Author(s)   : DataMetica Team
--#   Usage       : beeline -u  <url> -n <username> -p <password> -hivevar var1=var1 -f module.hql
--#   Date        : 05/02/2016
--#   Log File    : .../log/DDP_DEPLOYMENT.log
--#   SQL File    :
--#   Error File  : .../log/DDP_DEPLOYMENT.log
--#   Dependency  :
--#   Disclaimer  :
--#
--#   Modification History :
--#   =======================
--#
--#    ver     who                      date             comments
--#   ------   --------------------     ----------       -------------------------------------
--#    1.0     DataMetica Team          05/02/2016       Initial version
--#
--#
--#####################################################################################################################

DROP TABLE IF EXISTS ${hivevar:database}.${hivevar:table_prefix}${hivevar:table_name}
;

CREATE EXTERNAL TABLE ${hivevar:database}.${hivevar:table_prefix}${hivevar:table_name}
 (
   CORP      INT                 COMMENT 'FIVE DIGIT SYSTEM NUMBER ASSIGNED TO EACH CORP.',
   RCODE     VARCHAR(2)          COMMENT 'RATE CODE - TO CHARGE FOR A SERVICE OR COMBO OF SERVICES RATE TABLE ANY TWO ALPHA CHARACTERS. AZ-HZ ARE NON-STANDARD RATES AND CODES BEGINNING WITH IS XIS  ARE FREE RATES',
   RMULT     VARCHAR(1)          COMMENT 'FLAG INDICATING WHETHER THIS RATE CODE IS CHARGED BY CUSTOMER OR BY OUTLET 1=CHARGE BY OUTLET, <BLANK>=CHARGE BY CUSTOMER',
   RACTV     VARCHAR(1)          COMMENT 'FLAG INDICATING WHETHER OR NOT THIS RATE CODE IS CURRENTLY ACTIVE 1=RATE CODE IS INACTIVE <BLANK>=RATE CODE ACTIVE',
   RTYPE     VARCHAR(1)          COMMENT 'FLAG IDENTIFYING THIS RATE CODE AS A PRIMARY OR ADDITIONAL BASIC RATE CODE 1=PRIMARY RATE CODE, 2=ADDITIONAL RATE CODE <BLANK>=NORMAL RATE CODE',
   RCATG     VARCHAR(1)          COMMENT 'RATE CODE CATEGORY D=DEPOSIT, R=RENT, S=SERVICE, I=INSTALL',
   RCARRY    VARCHAR(1)          COMMENT 'FLAG INDICATING WHETHER THIS RATE CODE SHOULD BE CARRIED TO ADDITIONAL OUTLETS 1=CARRY <BLANK>=DONIS T CARRY',
   RNONSTD   VARCHAR(1)          COMMENT 'NON-STANDARD RATE CODE FLAG 1=NON STANDARD RATE CODE <BLANK>=REGULAR RATE CODE',
   RAMT      DECIMAL(6,2)        COMMENT 'DOLLAR AMOUNT TO CHARGE FOR THIS RATE CODE',
   RSRVGRP   VARCHAR(1)          COMMENT 'RATE CODE SERVICE GROUP, USED FOR REPORTING 1-9',
   RCOMBO    VARCHAR(1)          COMMENT 'IF SERVICE IS STANDALONE BUT COMBOIS S WITH OTHERS -THIS WILL BE THE SUPPLIER CODE. SUPPLIER CODE FOR THE STANDALONE SERVICE',
   RBOX      VARCHAR(2)          COMMENT 'EQUIPMENT TABLE CODE FOR THIS RATE CODE36 TABLE 119 <BLANK> OR 1-9,A-Z',
   RPRCODE   VARCHAR(2)          COMMENT 'NEW RATE CODE THAT WILL BE SWAPPED OVER TO WHEN THE PROMO CODE (RCODE FOR THIS ROW. EXPIRES',
   RACT1STRT VARCHAR(2)          COMMENT 'ACCOUNTING AREA RANGE NUMBER ONE START VALUE',
   RACT1STOP VARCHAR(2)          COMMENT 'ACCOUNTING AREA RANGE NUMBER 1 STOP VALUE',
   RACT2STRT VARCHAR(2)          COMMENT 'ACCOUNTING AREA RANGE NUMBER TWO START VALUE',
   RACT2STOP VARCHAR(2)          COMMENT 'ACCOUNTING AREA RANGE NUMBER TWO STOP VALUE',
   RACT3STRT VARCHAR(2)          COMMENT 'RATE CODE ACCOUNTING AREA RANGE 3 START VALUE',
   RACT3STOP VARCHAR(2)          COMMENT 'ACCOUNTING AREA RANGE NUMBER THREE STOP VALUE',
   RPRMONTH  INT                 COMMENT 'NUMBER OF MONTHS THIS PROMO CODE LASTS 1-95',
   RPAYS     INT                 COMMENT 'THE NUMBER OF PAY SERVICES THIS RATE CODE REPRESENTS',
   RDESC     VARCHAR(8)          COMMENT 'RATE CODE SHORT DESCRIPTION',
   RNAME     VARCHAR(16)         COMMENT 'RATE CODE DESCRIPTION',
   RCOMBOS   VARCHAR(15)         COMMENT 'LIST OF SUPPLIER CODES THAT INDICATES THE SERVICESCOMBINED TO MAKE THIS COMBO CODE. TABLE 104. A-Z',
   TASK1REM  VARCHAR(3)          COMMENT 'TASK GROUP ONE TASK CODE FOR REMOVING THIS RATE CODE CODE95 TABLE 201',
   TASK1SLOT  VARCHAR(1)          COMMENT 'TASK COUNT SLOT FOR TASK GROUP ONE CODE36 TABLE 127',
   TSK1APTOV1  VARCHAR(3)         COMMENT 'TASK GROUP ONE TASK CODE FOR OVERHEAD APARTMENT INSTALLS CODE95 TABLE 201',
   TSK1APTUG1  VARCHAR(3)         COMMENT 'TASK GROUP ONE TASK CODE FOR UNDERGROUND APARTMENT INSTALLS CODE95 TABLE 201',
   TSK1HSOV1   VARCHAR(3)         COMMENT 'TASK GROUP ONE TASK CODE FOR OVERHEAD HOUSE INSTALLS CODE95 TABLE 201',
   TSK1HSUG1   VARCHAR(3)         COMMENT 'TASK GROUP ONE TASK CODE FOR UNDERGROUND HOUSE INSTALLS CODE95 TABLE 201',
   TSK1APTOV2  VARCHAR(3)         COMMENT 'TASK GROUP ONE TASK CODE FOR OVERHEAD APARTMENT RECONNECTS CODE95 TABLE 201',
   TSK1APTUG2  VARCHAR(3)         COMMENT 'TASK GROUP ONE TASK CODE FOR UNDERGROUND APARTMENT RECONNECTS CODE95 TABLE 201',
   TSK1HSOV2   VARCHAR(3)         COMMENT 'TASK GROUP ONE TASK CODE FOR OVERHEAD HOUSE RECONNECTS CODE95 TABLE 201',
   TSK1HSUG2   VARCHAR(3)         COMMENT 'TASK GROUP ONE TASK CODE FOR UNDERGROUND HOUSE RECONNECTS CODE95 TABLE 201',
   TASK2REM    VARCHAR(3)         COMMENT 'TASK GROUP TWO TASK CODE FOR REMOVING THIS RATE CODE CODE95 TABLE 201',
   TASK2SLOT   VARCHAR(1)         COMMENT 'TASK COUNT SLOT FOR TASK GROUP TWO',
   TSK2APTOV1  VARCHAR(3)         COMMENT 'TASK GROUP TWO TASK CODE FOR OVERHAEAD APARTMENT INSTALLS CODE95 TABLE 201',
   TSK2APTUG1  VARCHAR(3)         COMMENT 'TASK GROUP 2 TASK CODE FOR UNDERGROUND APARTMENT INSTALLS CODE95 TABLE 201',
   TSK2HSOV1   VARCHAR(3)         COMMENT 'TASK GROUP 2 TASK CODE FOR OVERHEAD HOUSE INSTALLS CODE95 TABLE 201',
   TSK2HSUG1   VARCHAR(3)         COMMENT 'TASK GROUP TWO TASK CODE FOR UNDERGROUND HOUSE INSTALLS CODE95 TABLE 201',
   TSK2APTOV2  VARCHAR(3)         COMMENT 'TASK GROUP TWO TASK CODE FOR OVERHEAD APARTMENT RECONNECTS CODE95 TABLE 201',
   TSK2APTUG2  VARCHAR(3)         COMMENT 'TASK GORUP TWO TASK CODE FOR UNDERGROUND APARTMENT RECONNECTS CODE95 TABLE 201',
   TSK2HSOV2   VARCHAR(3)         COMMENT 'TASK GROUP TWO TASK CODE FOR OVERHEAD HOUSE RECONNECTS CODE95 TABLE 201',
   TSK2HSUG2   VARCHAR(3)         COMMENT 'TASK GROUP TWO TASK CODE FOR UNDERGROUND HOUSE RECONNECTS CODE95 TABLE 201',
   TASK3REM    VARCHAR(3)         COMMENT 'TASK GROUP THREE TASK CODE FOR REMOVING THIS RATE CODE CODE95 TABLE 201',
   TASK3SLOT   VARCHAR(1)         COMMENT 'TASK COUNT SLOT FOR TASK GROUP 3',
   TSK3APTOV1  VARCHAR(3)         COMMENT 'TASK GROUP THREE TASK CODE FOR OVERHEAD APARTMENT INSTALLS CODE95 TABLE 201',
   TSK3APTUG1  VARCHAR(3)         COMMENT 'TASK GROUP THREE TASK CODE FOR UNDERGROUND APARTMENT INSTALLS CODE95 TABLE 201',
   TSK3HSOV1   VARCHAR(3)         COMMENT 'TASK GROUP THREE TASK CODE FOR OVERHEAD HOUSE INSTALLS CODE95 TABLE 201',
   TSK3HSUG1   VARCHAR(3)         COMMENT 'TASK GROUP THREE TASK CODE FOR UNDERGROUND HOUSE INSTALLS CODE95 TABLE 201',
   TSK3APTOV2  VARCHAR(3)         COMMENT 'TASK GROUP THREE TASK CODE FOR OVERHEAD APARTMENT RECONNECTS CODE95 TABLE 201',
   TSK3APTUG2  VARCHAR(3)         COMMENT 'TASK GROUP THREE TASK CODE FOR UNDERGROUND APARTMENT RECONNECTS CODE95 TABLE 201',
   TSK3HSOV2   VARCHAR(3)         COMMENT 'TASK GROUP THREE TASK CODE FOR OVERHEAD HOUSE RECONNECTS CODE95 TABLE 201',
   TSK3HSUG2   VARCHAR(3)         COMMENT 'TASK GROUP THREE TASK CODE FOR UNDERGROUND HOUSE RECONNECTS CODE95 TABLE 201',
   RAUTH01     VARCHAR(3)         COMMENT 'ADDRESSABLE AUTHORIZATION CODE ONE 0-63',
   RAUTH02     VARCHAR(3)         COMMENT 'ADDRESSABLE AUTHORIZATION CODE TWO',
   RAUTH03     VARCHAR(3)         COMMENT 'ADDRESSABLE AUTHORIZATION CODE THREE',
   RAUTH04     VARCHAR(3)         COMMENT 'ADDRESSABLE AUTHORIZATION CODE FOUR 0-63',
   RAUTH05     VARCHAR(3)         COMMENT 'ADDRESSABLE AUTHORIZATION CODE FIVE 0-63',
   RAUTH06     VARCHAR(3)         COMMENT 'ADDRESSABLE AUTHORIZATION CODE SIX 0-63',
   RAUTH07     VARCHAR(3)         COMMENT 'ADDRESSABLE AUTHORIZATION SEVEN 0-63',
   RAUTH08     VARCHAR(3)         COMMENT 'ADDRESSABLE AUTHORIZATION CODE EIGHT 0-63',
   RAUTH09     VARCHAR(3)         COMMENT 'ADDRESSABLE AUTHORIZATION CODE NINE 0-63',
   RAUTH10     VARCHAR(3)         COMMENT 'ADDRESSABLE AUTHORIZATION CODE TEN 0-63',
   RAUTH11     VARCHAR(3)         COMMENT 'ADDRESSABLE AUTHORIZATION CODE ELEVEN 0-63',
   RAUTH12     VARCHAR(3)         COMMENT 'ADDRESSABLE AUTHORIZATION CODE 12 0-63',
   RAUTH13     VARCHAR(3)         COMMENT 'ADDRESSABLE AUTHORIZATION CODE THIRTEEN 0-63',
   RAUTH14     VARCHAR(3)         COMMENT 'ADDRESSABLE AUTHORIZATION CODE FOURTEEN 0-63',
   RAUTH15     VARCHAR(3)         COMMENT 'ADDRESSABLE AUTHORIZATION CODE FIFTEEN 0-63',
   RAUTH16     VARCHAR(3)         COMMENT 'ADDRESSABLE AUTHORIZATION CODE SIXTEEN 0-63',
   RAUTH17     VARCHAR(3)         COMMENT 'ADDRESSABLE AUTHORIZATION CODE SEVENTEEN 0-63',
   RAUTH18     VARCHAR(3)         COMMENT 'ADDRESSABLE AUTHORIZATION CODE EIGHTEEN 0-63',
   RAUTH19     VARCHAR(3)         COMMENT 'ADDRESSABLE AUTHORIZATION CODE NINETEEN 0-63',
   RAUTH20     VARCHAR(3)         COMMENT 'ADDRESSABLE AUTHORIZATION CODE TWENTY 0-63',
   RDISCOD1    VARCHAR(2)         COMMENT 'RATE CODE NUMBER ONE FOR MULTIPLE OUTLET DISCOUNTING',
   RDISCOD2    VARCHAR(2)         COMMENT 'RATE CODE NUMBER TWO FOR MULTIPLE OUTLET DISCOUNTING',
   RDISCOD3    VARCHAR(2)         COMMENT 'RATE CODE NUMBER THREE FOR MULTIPLE OUTLET DISCOUNTING',
   RDISCOD4    VARCHAR(2)         COMMENT 'RATE CODE NUMBER FOUR FOR MULTIPLE OUTLET DISCOUNTING',
   RDISCOD5    VARCHAR(2)         COMMENT 'RATE CODE NUMBER FIVE FOR MULTIPLE OUTLET DISCOUNTING',
   RDISCOD6    VARCHAR(2)         COMMENT 'RATE CODE NUMBER SIX FOR MULTIPLE OUTLET DISCOUNTING',
   PRIORAMT    DECIMAL(6,2)       COMMENT 'THE DOLLAR AMOUNT FOR THIS RATE CODE PRIOR TO THE NEW RATE BEING PUT INTO RAMT',
   EFFDATE     DATE               COMMENT 'THE EFFECTIVE DATE FOR A RATE CHANGE ON THIS RATE CODE',
   ACTVONCYC   VARCHAR(1)         COMMENT 'FLAGS WHEN PRORATE RUN IS EFFECTIVE. Y=PRORATE RUN EFFECTIVE ON CYCLE N=PRORATE RUN EFFECTIVE ON DATE PRORATE RUN WAS RUN',
   PRORATEONCYC   VARCHAR(1)      COMMENT 'FLAG THAT INDICATES HOW TO HANDLE A CUSTOMER WHO HAD PRORATE WITH THIS RATE CODE DURING A R/I Y=PRORATE AT OLD AMOUNT N=CHARGE NEW RATE IN PRORATE FROM R/I EFF. DATE',
   MSORCODE    VARCHAR(2)         COMMENT 'MSO R CODE',
   FORMAT      VARCHAR(1)         COMMENT '',
   DIGITAL     INT                COMMENT '',
   DELIVERYSYSID   VARCHAR(20)    COMMENT '',
   MACHINE_ID      VARCHAR(5)     COMMENT 'THE ID OF THE TANDEM THAT THE ORIGINAL RECORD WAS EXTRACTED FROM',
   OP_TYPE         VARCHAR(1)     COMMENT 'GOLDEN GATE ASSIGNED OPERATION TYPE THAT DESCRIPBES THE ORIGINAL OPERATION THE',
   LOAD_DATE       TIMESTAMP      COMMENT 'ORACLE ASSIGNED DATE OF WHEN THE RECORD WAS LOADED INTO THE ORACLE DATABASE',
   RATECODES_SEQ   BIGINT         COMMENT '',
   ADDRESSABLE     INT            COMMENT '',
   GGS_TRANS_TIMESTAMP   VARCHAR(26)   COMMENT 'GOLDEN GATE ASSIGNED DATE FOR WHICH THE TRANSACTION OCCURRED ON THE TANDEM',
   JOBEDT          VARCHAR(1)     COMMENT '',
   LOB_SUBTYPE     INT            COMMENT '',
   PRIMARYDEFLTCNT VARCHAR(1)     COMMENT '',
   PRODCT_ID       INT            COMMENT '',
   RESTRICTED      INT            COMMENT '',
   SECONDARYDEFLTCNT   VARCHAR(1)   COMMENT '',
   TASKGP          INT              COMMENT '',
   TN_PRIMARY      VARCHAR(3)       COMMENT '',
   VERSION_NUMBER  INT              COMMENT '',
   VOIP_RATE_TYPE  VARCHAR(1)       COMMENT ''
)
PARTITIONED BY (LOAD_YEAR STRING,
                LOAD_MONTH STRING)
STORED AS AVRO
LOCATION '${hivevar:location}'
;

--##############################################################################
--#                                    End                                     #
--##############################################################################
