CREATE TABLE MDRMGR.UNIQUE_VISITOR_AGG
(
  VISIT_DATE             DATE,
  COUNT_TYPE             VARCHAR2(20 BYTE),
  COUNT_TYPE_ID          INTEGER,
  COUNT_TYPE_VALUE       VARCHAR2(750 BYTE),
  VISID_COUNT            INTEGER,
  OPTIMUM_ID_COUNT       INTEGER,
  CORP_HOUSE_CUST_COUNT  INTEGER,
  PERIOD_START_DATE      DATE,
  PERIOD_END_DATE        DATE,
  DTM_CREATED            TIMESTAMP(6) WITH LOCAL TIME ZONE,
  SOURCED_FROM_SYSTEM    VARCHAR2(255 BYTE),
  SUITE_NAME             VARCHAR2(255 BYTE),
  FREQUENCY              VARCHAR2(20 BYTE),
  PERIOD                 VARCHAR2(50 BYTE)
)
TABLESPACE MDRD_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT SELECT ON MDRMGR.UNIQUE_VISITOR_AGG TO MDR_SELECT_DEV;

GRANT SELECT ON MDRMGR.UNIQUE_VISITOR_AGG TO MDRUSR WITH GRANT OPTION;
GRANT DELETE, INSERT, UPDATE ON MDRMGR.UNIQUE_VISITOR_AGG TO MDRUSR;